## Basic app
server.port=8081
spring.application.name=geelato-sample-quickstart

## Starter base: in-memory primary datasource
spring.datasource.primary.name=primary
spring.datasource.primary.jdbc-url=jdbc:h2:mem:geelato_sample;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
spring.datasource.primary.driver-class-name=org.h2.Driver
spring.datasource.primary.username=sa
spring.datasource.primary.password=

## Starter base: ORM and dynamic datasource
geelato.orm.dao-bean-name=dynamicDao
geelato.datasource.dynamic.enable-jta-transaction=false
geelato.datasource.dynamic.enable-seata-proxy=false

## Logging
logging.level.root=INFO
logging.level.cn.geelato=INFO
